"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _album_detail from './album-detail.bones.json'
import _artist_albums_grid from './artist-albums-grid.bones.json'
import _artist_header from './artist-header.bones.json'
import _listening_calendar from './listening-calendar.bones.json'
import _listening_trend_chart from './listening-trend-chart.bones.json'
import _recent_spins_list from './recent-spins-list.bones.json'
import _shop_floor_album_grid from './shop-floor-album-grid.bones.json'
import _top_artists_list from './top-artists-list.bones.json'
import _top_genres_chart from './top-genres-chart.bones.json'

registerBones({
  "album-detail": _album_detail,
  "artist-albums-grid": _artist_albums_grid,
  "artist-header": _artist_header,
  "listening-calendar": _listening_calendar,
  "listening-trend-chart": _listening_trend_chart,
  "recent-spins-list": _recent_spins_list,
  "shop-floor-album-grid": _shop_floor_album_grid,
  "top-artists-list": _top_artists_list,
  "top-genres-chart": _top_genres_chart,
})
